export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  COUNSELLING_SCHEDULED = 'COUNSELLING_SCHEDULED',
  CAMPUS_VISIT_SCHEDULED = 'CAMPUS_VISIT_SCHEDULED',
  CAMPUS_VISITED = 'CAMPUS_VISITED',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  DROPPED = 'DROPPED',
  CONVERTED = 'CONVERTED',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DOCUMENT_VERIFIED = 'DOCUMENT_VERIFIED',
  ASSESSMENT_PENDING = 'ASSESSMENT_PENDING',
  ASSESSMENT_COMPLETED = 'ASSESSMENT_COMPLETED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FEE_PENDING = 'FEE_PENDING',
  FEE_PAID = 'FEE_PAID',
  ENROLLED = 'ENROLLED',
}

export enum FeePaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}
