export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  ADMISSION_OFFICER: 'ADMISSION_OFFICER',
  COUNSELLOR: 'COUNSELLOR',
  ACADEMIC_ADMIN: 'ACADEMIC_ADMIN',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  STAFF: 'STAFF',
} as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];
