[build]
  base = "apps/web_app"
  command = "pnpm install --frozen-lockfile && pnpm --filter @edutrack/web run build"
  publish = "dist"

[context.production.environment]
  # Pointing to the Render Backend
  VITE_API_URL = "https://appsms-076a.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
