import { FEATURE_FLAGS } from '../constants/featureFlags';

export const FEATURE_FLAGS_CONFIG: Record<string, boolean> = {
    // Defaults for UAT/Dev environments
    [FEATURE_FLAGS.ADMISSION.LEAD_MODULE]: true,
    [FEATURE_FLAGS.ADMISSION.EXAM_SCHEDULING]: true,
    [FEATURE_FLAGS.ADMISSION.EVALUATION_DESK]: true,
    [FEATURE_FLAGS.ADMISSION.MERIT_ENGINE]: true,
    [FEATURE_FLAGS.ADMISSION.PAYMENT_INTEGRATION]: true,

    [FEATURE_FLAGS.STUDENT.SIS_FOUNDATION]: true,
    [FEATURE_FLAGS.STUDENT.ACADEMIC_HISTORY]: true,
    [FEATURE_FLAGS.STUDENT.PROMOTION_TRACKER]: true,
    [FEATURE_FLAGS.STUDENT.IDENTITY_CARDS]: true,

    [FEATURE_FLAGS.ATTENDANCE.DAILY_MARKING]: true,
    [FEATURE_FLAGS.ATTENDANCE.PERIOD_ATTENDANCE]: true,
    [FEATURE_FLAGS.ATTENDANCE.LEAVE_BALANCES]: true,
    [FEATURE_FLAGS.ATTENDANCE.BIOMETRIC_DEVICE]: true,
    [FEATURE_FLAGS.ATTENDANCE.ANALYTICS]: true,
};
