import { PERMISSIONS } from '../constants/permissions';

export const ROLE_PERMISSIONS_MAPPING: Record<string, string[]> = {
    SUPERADMIN: [
        PERMISSIONS.DASHBOARD.VIEW_ADMIN,
        PERMISSIONS.ADMISSION.VIEW_ALL,
        PERMISSIONS.ADMISSION.REVIEW,
        PERMISSIONS.STUDENT.VIEW,
        PERMISSIONS.STUDENT.CREATE,
        PERMISSIONS.STUDENT.PROMOTE,
        PERMISSIONS.ATTENDANCE.MARK,
        PERMISSIONS.ATTENDANCE.VERIFY,
    ],
    ADMIN: [
        PERMISSIONS.DASHBOARD.VIEW_ADMIN,
        PERMISSIONS.ADMISSION.VIEW_ALL,
        PERMISSIONS.ADMISSION.REVIEW,
        PERMISSIONS.STUDENT.VIEW,
        PERMISSIONS.STUDENT.CREATE,
        PERMISSIONS.STUDENT.PROMOTE,
        PERMISSIONS.ATTENDANCE.MARK,
        PERMISSIONS.ATTENDANCE.VERIFY,
    ],
    TEACHER: [
        PERMISSIONS.DASHBOARD.VIEW_STAFF,
        PERMISSIONS.STUDENT.VIEW,
        PERMISSIONS.ATTENDANCE.MARK,
        PERMISSIONS.ATTENDANCE.LEAVE_APPROVE,
    ],
    STUDENT: [
        PERMISSIONS.DASHBOARD.VIEW_STUDENT,
        PERMISSIONS.STUDENT.VIEW_SELF,
    ],
    PARENT: [
        PERMISSIONS.DASHBOARD.VIEW_STUDENT,
        PERMISSIONS.STUDENT.VIEW_SELF,
        PERMISSIONS.ATTENDANCE.LEAVE_APPLY,
    ]
};
