import { UserRole } from '../types/role.types';

export const USER_ROLES: Record<UserRole, UserRole> = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  ADMISSION_OFFICER: 'ADMISSION_OFFICER',
  COUNSELOR: 'COUNSELOR',
  PRINCIPAL: 'PRINCIPAL',
  ACADEMIC_COORDINATOR: 'ACADEMIC_COORDINATOR',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
  ACCOUNTANT: 'ACCOUNTANT',
  HR: 'HR',
  TRANSPORT_MANAGER: 'TRANSPORT_MANAGER',
  LIBRARIAN: 'LIBRARIAN',
  HOSTEL_WARDEN: 'HOSTEL_WARDEN',
  RECEPTION: 'RECEPTION',
  SECURITY: 'SECURITY',
  MANAGEMENT: 'MANAGEMENT',
};
