export const FEATURE_FLAGS = {
  ENABLE_BIOMETRICS: true,
  ENABLE_OFFLINE_SYNC: true,
  ENABLE_PUSH_NOTIFICATIONS: true,
  ENABLE_MULTI_TENANT_WORKSPACE: true,
  ENABLE_CRASHLYTICS: false,
  ENABLE_ANALYTICS: false,
};
