import { UserRole } from '../types/role.types';

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  SUPER_ADMIN: ['ALL'],
  SCHOOL_ADMIN: ['ALL'],
  ADMISSION_OFFICER: ['ADMISSION_CREATE', 'ADMISSION_READ', 'ADMISSION_UPDATE'],
  COUNSELOR: ['ADMISSION_READ', 'STUDENT_READ'],
  PRINCIPAL: ['ALL_READ', 'REPORTS_VIEW', 'APPROVE'],
  ACADEMIC_COORDINATOR: ['TEACHER_READ', 'STUDENT_READ', 'LMS_MANAGE'],
  TEACHER: ['STUDENT_READ', 'ATTENDANCE_MARK', 'GRADES_ENTER'],
  PARENT: ['CHILD_READ', 'FEES_PAY', 'COMMUNICATION_VIEW'],
  STUDENT: ['PROFILE_READ', 'GRADES_VIEW', 'TIMETABLE_VIEW'],
  ACCOUNTANT: ['FINANCE_ALL'],
  HR: ['HR_ALL'],
  TRANSPORT_MANAGER: ['TRANSPORT_ALL'],
  LIBRARIAN: ['LIBRARY_ALL'],
  HOSTEL_WARDEN: ['HOSTEL_ALL'],
  RECEPTION: ['VISITOR_ALL'],
  SECURITY: ['GATE_PASS_ALL'],
  MANAGEMENT: ['DASHBOARD_ALL', 'REPORTS_ALL'],
};
