module.exports = {
  env: {
    node: true,
    es2022: true,
  },
  extends: ['eslint:recommended'],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  ignorePatterns: ['dist', 'build', '.turbo', 'coverage', 'node_modules', 'public', '.expo'],
  rules: {
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    'no-undef': 'off',
    'no-empty': 'warn',
    'no-extra-boolean-cast': 'warn',
    'no-useless-escape': 'warn',
    'no-case-declarations': 'warn',
    'no-control-regex': 'warn',
    'no-regex-spaces': 'warn',
    'no-debugger': 'warn',
    'no-prototype-builtins': 'warn',
    'no-cond-assign': 'warn',
    'no-constant-condition': 'warn',
    'no-fallthrough': 'warn',
    'no-async-promise-executor': 'warn',
    'no-misleading-character-class': 'warn',
    'no-shadow-restricted-names': 'warn',
    'no-unexpected-multiline': 'warn',
    'no-unreachable': 'warn',
    'no-unsafe-finally': 'warn',
    'no-unsafe-negation': 'warn',
    'no-unsafe-optional-chaining': 'warn',
    'no-redeclare': 'warn',
    'no-dupe-keys': 'warn',
    'no-dupe-class-members': 'warn',
    'no-dupe-args': 'warn',
    'no-dupe-else-if': 'warn',
    'no-sparse-arrays': 'warn',
    'no-func-assign': 'warn',
    'no-class-assign': 'warn',
    'no-import-assign': 'warn',
    'no-const-assign': 'warn',
    'no-obj-calls': 'warn',
    'no-setter-return': 'warn',
    'getter-return': 'warn',
    'constructor-super': 'warn',
    'no-this-before-super': 'warn',
    'require-yield': 'warn',
    'use-isnan': 'warn',
    'valid-typeof': 'warn',
  },
};
