export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  ORGANIZATION: {
    PROFILE: '/organization/profile',
    UPDATE: '/organization/update',
    SETTINGS: '/organization/settings',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
    ROLES: '/users/roles',
    PERMISSIONS: '/users/permissions',
  },
  HR: {
    DEPARTMENTS: '/hr/departments',
    DESIGNATIONS: '/hr/designations',
    STAFF: '/v1/staff',
    STAFF_COUNSELLORS: '/v1/staff/counsellors',
    STAFF_BY_ID: (id: string) => `/v1/staff/${id}`,
  },
  ACADEMICS: {
    YEARS: '/academics/years',
    GRADES: '/academics/grades',
    SECTIONS: '/academics/sections',
  },
  CRM: {
    LEADS: '/v1/leads',
    LEAD_BY_ID: (id: string) => `/v1/leads/${id}`,
    LEAD_ACTIVITIES: (leadId: string) => `/v1/leads/${leadId}/activities`,
    CAMPUS_VISITS: '/v1/leads/visits',
    QUALIFY: (leadId: string) => `/v1/leads/${leadId}/qualify`,
    CONVERT: (leadId: string) => `/v1/leads/${leadId}/convert`,
  },
  ADMISSIONS: {
    APPLICATIONS: '/v1/applications',
    APPLICATION_BY_ID: (id: string) => `/v1/applications/${id}`,
    DOCUMENTS: (appId: string) => `/v1/applications/${appId}/documents`,
    DOCUMENT_VERIFY: (docId: string) => `/v1/applications/documents/${docId}/verify`,
    DOCUMENT_SIGNED_URL: (docId: string) => `/v1/applications/documents/${docId}/signed-url`,
    DOCUMENT_DELETE: (docId: string) => `/v1/applications/documents/${docId}`,
    DOCUMENT_TYPES: '/v1/applications/document-types',
    PENDING: '/v1/applications/pending',
    DASHBOARD: '/v1/applications/dashboard',
    ASSESSMENT: (appId: string) => `/v1/applications/${appId}/assessment`,
    ASSESSMENT_CONFIGS: '/v1/applications/assessment-configs',
    ASSESSMENT_ANALYTICS: '/v1/applications/assessment-analytics',
    ASSESSMENTS_LIST: '/v1/applications/assessments',
    EXAMINERS: '/v1/applications/examiners',
    DECISION: (appId: string) => `/v1/applications/${appId}/decision`,
    FEES: (appId: string) => `/v1/applications/${appId}/fees`,
    FEE_INFO: (appId: string) => `/v1/applications/${appId}/fee`,
    PAYMENT: (appId: string) => `/v1/applications/${appId}/payment`,
    RECEIPT: (appId: string) => `/v1/applications/${appId}/receipt`,
    FEE_CONFIG: '/v1/applications/fee-config',
  },
  STUDENTS: {
    DIRECTORY: '/v1/students',
    STUDENT_BY_ID: (id: string) => `/v1/students/${id}`,
    APPROVED_APPLICATIONS: '/v1/students/approved-applications',
    CONVERT_APPLICATION: (appId: string) => `/v1/students/convert-application/${appId}`,
    ASSIGN_SECTION: (enrollmentId: string) => `/v1/students/enrollments/${enrollmentId}/section`,
    PARENTS: (studentId: string) => `/v1/students/${studentId}/parents`,
  },
  REPORTS: {
    ADMISSIONS: '/reports/admissions',
    STUDENTS: '/reports/students',
    FINANCIAL: '/reports/financial',
  },
  AUDIT: {
    LOGS: '/audit/logs',
  },
  CHATBOT: {
    CREATE_SESSION: '/v1/chatbot/session',
    SEND_MESSAGE: '/v1/chatbot/message',
    GET_SESSION: (sessionId: string) => `/v1/chatbot/session/${sessionId}`,
    COMPLETE_SESSION: (sessionId: string) => `/v1/chatbot/session/${sessionId}/complete`,
  },

  NOTIFICATIONS: {
    BASE: '/v1/notifications',
    UNREAD_COUNT: '/v1/notifications/unread-count',
    MARK_READ: (id: string) => `/v1/notifications/${id}/read`,
    MARK_ALL_READ: '/v1/notifications/mark-all-read',
    BY_ID: (id: string) => `/v1/notifications/${id}`,
  },
} as const;
